import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
// Generated by `docusaurus gen-api-docs` from openapi.json (pnpm run openapi): not versioned. It exports the items.
import apiItems from './api/sidebar';

const sidebars: SidebarsConfig = { api: apiItems };

export default sidebars;
