import { describe, expect, it } from 'vitest';
import { checkContributionRow } from './contribution-rows.js';

const forense = { section: 'OTHER_ENTITY' as const, entityCode: '0013', reason: 'E100', periodFrom: '01/2026', periodTo: '12/2026', amount: 1000 };

describe('checkContributionRow – other entities (AdE tables and resolutions of each fund)', () => {
  it('accepts a Cassa Forense row and deducts the personal contribution (LM35)', () => {
    const r = checkContributionRow(forense);
    expect(r.errors).toEqual([]);
    expect(r.deductibleAmount).toBe(1000);
    expect(r.description).toMatch(/^Cassa Forense - /);
  });

  it('does not deduct the contribution charged on invoices ("integrativo", Ris. AdE 69/E/2006)', () => {
    expect(checkContributionRow({ ...forense, reason: 'E103' }).deductibleAmount).toBe(0);
  });

  it('refuses unknown entities and reasons, office and position codes where the entity wants them empty', () => {
    expect(checkContributionRow({ ...forense, entityCode: '9999' }).errors[0]).toMatch(/Codice ente 9999/);
    expect(checkContributionRow({ ...forense, reason: 'E999' }).errors).toContain('La causale E999 non è tra quelle di Cassa Forense');
    expect(checkContributionRow({ ...forense, officeCode: '5500', positionCode: '123' }).errors).toHaveLength(2);
  });

  it('checks the period: MM/YYYY not reversed; ENPAP only the year ("Formato AAAA")', () => {
    expect(checkContributionRow({ ...forense, periodFrom: '12/2026', periodTo: '01/2026' }).errors).toContain('L\'inizio del periodo non può essere dopo la fine');
    expect(checkContributionRow({ ...forense, periodTo: '2026' }).errors).toContain('Periodo di riferimento da MM/AAAA a MM/AAAA');
    const enpap = { section: 'OTHER_ENTITY' as const, entityCode: '0007', reason: 'ECTR', periodFrom: '2026', amount: 500 };
    expect(checkContributionRow(enpap).errors).toEqual([]);
    expect(checkContributionRow({ ...enpap, periodTo: '12/2026' }).errors).toHaveLength(1);
  });

  it('asks CNPADC for the position code generated by the fund (up to 9 digits)', () => {
    const cnpadc = { section: 'OTHER_ENTITY' as const, entityCode: '0015', reason: 'E150', periodFrom: '01/2026', periodTo: '12/2026', amount: 800 };
    expect(checkContributionRow(cnpadc).errors).toHaveLength(1);
    expect(checkContributionRow({ ...cnpadc, positionCode: '123456789' }).errors).toEqual([]);
  });

  it('INPS Artigiani and Commercianti rows: office, 17-digit INPS code, reasons of the INPS sheet', () => {
    const af = { section: 'INPS' as const, officeCode: '5500', reason: 'AF', positionCode: '11111112261000003', periodFrom: '01/2026', periodTo: '12/2026', amount: 1130.34 };
    expect(checkContributionRow(af)).toMatchObject({ errors: [], deductibleAmount: 1130.34, description: 'INPS Artigiani - Contributi dovuti sul minimale di reddito' });
    expect(checkContributionRow({ ...af, reason: 'CPI' }).deductibleAmount).toBe(0);
    expect(checkContributionRow({ ...af, positionCode: '123', officeCode: undefined }).errors).toHaveLength(2);
    expect(checkContributionRow({ ...af, reason: 'PXX' }).errors[0]).toMatch(/non è tra quelle di Artigiani e Commercianti/);
  });
});
