/**
 * INPS office codes ("codice sede") for the F24 INPS section.
 * Source: AdE, "Tabella codici sede INPS" (Strumenti -> Codici per i versamenti), read on 2026-09-21:
 * https://www.agenziaentrate.gov.it/portale/strumenti/codici-attivita-e-tributo/f24-codici-tributo-per-i-versamenti/tabelle-dei-codici-tributo-e-altri-codici-per-il-modello-f24/tabelle-codici-inps-e-enti-previdenziali-ed-assicurativi/tabella-codici-sede-inps
 * Columns: medical checks / artisans and traders / other contributions (the one relevant to Gestione Separata).
 * Codes are 4 digits, zero-padded (the table prints e.g. "100" for Agrigento).
 * Note: the official table lists code 8103 twice ("Torino Nord" and "Torino Sud"); both rows are kept as published.
 */
export interface InpsOffice {
  /** Unique id "<code>-<name slug>" (the code alone is not unique in the official table). */
  id: string;
  code: string;
  name: string;
  medicalChecks: boolean;
  artisansTraders: boolean;
  otherContributions: boolean;
}

export const INPS_OFFICES: readonly InpsOffice[] = [
  { id: '0100-agrigento', code: '0100', name: 'Agrigento', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '0101-sciacca', code: '0101', name: 'Sciacca', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '0200-alessandria', code: '0200', name: 'Alessandria', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '0300-ancona', code: '0300', name: 'Ancona', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '0391-jesi', code: '0391', name: 'Jesi', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '0400-aosta', code: '0400', name: 'Aosta', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '0500-arezzo', code: '0500', name: 'Arezzo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '0600-ascoli-piceno', code: '0600', name: 'Ascoli Piceno', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '0690-fermo', code: '0690', name: 'Fermo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '0700-asti', code: '0700', name: 'Asti', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '0800-avellino', code: '0800', name: 'Avellino', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '0890-ariano-irpino', code: '0890', name: 'Ariano Irpino', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '0900-bari', code: '0900', name: 'Bari', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '0901-andria', code: '0901', name: 'Andria', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '0993-gioia-del-colle', code: '0993', name: 'Gioia del Colle', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '1000-belluno', code: '1000', name: 'Belluno', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '1100-benevento', code: '1100', name: 'Benevento', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '1200-bergamo', code: '1200', name: 'Bergamo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '1300-bologna', code: '1300', name: 'Bologna', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '1301-imola', code: '1301', name: 'Imola', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '1393-san-lazzaro-di-savena', code: '1393', name: 'San Lazzaro di Savena', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '1400-bolzano', code: '1400', name: 'Bolzano', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '1491-merano', code: '1491', name: 'Merano', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '1500-brescia', code: '1500', name: 'Brescia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '1594-manerbio', code: '1594', name: 'Manerbio', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '1595-chiari', code: '1595', name: 'Chiari', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '1600-brindisi', code: '1600', name: 'Brindisi', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '1700-cagliari', code: '1700', name: 'Cagliari', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '1701-iglesias', code: '1701', name: 'Iglesias', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '1791-quartu-sant-elena', code: '1791', name: 'Quartu Sant\'Elena', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '1800-caltanissetta', code: '1800', name: 'Caltanissetta', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '1900-campobasso', code: '1900', name: 'Campobasso', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '1990-termoli', code: '1990', name: 'Termoli', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '2000-caserta', code: '2000', name: 'Caserta', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '2001-aversa', code: '2001', name: 'Aversa', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '2100-catania', code: '2100', name: 'Catania', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '2190-caltagirone', code: '2190', name: 'Caltagirone', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '2200-catanzaro', code: '2200', name: 'Catanzaro', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '2201-lamezia-terme', code: '2201', name: 'Lamezia Terme', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '2202-vibo-valenzia', code: '2202', name: 'Vibo Valenzia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '2203-crotone', code: '2203', name: 'Crotone', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '2300-chieti', code: '2300', name: 'Chieti', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '2391-vasto', code: '2391', name: 'Vasto', medicalChecks: true, artisansTraders: true, otherContributions: false },
  { id: '2400-como', code: '2400', name: 'Como', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '2401-lecco', code: '2401', name: 'Lecco', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '2490-cantu', code: '2490', name: 'Cantù', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '2500-cosenza', code: '2500', name: 'Cosenza', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '2501-rossano-calabro', code: '2501', name: 'Rossano Calabro', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '2590-paola', code: '2590', name: 'Paola', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '2591-castrovillari', code: '2591', name: 'Castrovillari', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '2600-cremona', code: '2600', name: 'Cremona', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '2700-cuneo', code: '2700', name: 'Cuneo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '2791-alba-c-o', code: '2791', name: 'Alba C.O', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '2792-mondovi', code: '2792', name: 'Mondovì', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '2800-enna', code: '2800', name: 'Enna', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '2900-ferrara', code: '2900', name: 'Ferrara', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3000-firenze', code: '3000', name: 'Firenze', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3001-prato', code: '3001', name: 'Prato', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3090-empoli-c-o', code: '3090', name: 'Empoli C.O', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3093-scandicci', code: '3093', name: 'Scandicci', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '3094-sesto-fiorentino', code: '3094', name: 'Sesto Fiorentino', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '3100-foggia', code: '3100', name: 'Foggia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3191-san-severo', code: '3191', name: 'San Severo', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '3200-forli', code: '3200', name: 'Forli\'', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3201-rimini', code: '3201', name: 'Rimini', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3290-cesena-c-o', code: '3290', name: 'Cesena C.O.', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3300-frosinone', code: '3300', name: 'Frosinone', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3301-cassino', code: '3301', name: 'Cassino', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3400-genova', code: '3400', name: 'Genova', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3401-sestri-levante', code: '3401', name: 'Sestri Levante', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3402-sestri-ponente', code: '3402', name: 'Sestri Ponente', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3500-gorizia', code: '3500', name: 'Gorizia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3600-grosseto', code: '3600', name: 'Grosseto', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3700-imperia', code: '3700', name: 'Imperia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3800-l-aquila', code: '3800', name: 'L\'Aquila', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3801-sulmona', code: '3801', name: 'Sulmona', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3802-avezzano', code: '3802', name: 'Avezzano', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '3900-la-spezia', code: '3900', name: 'La Spezia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4000-latina', code: '4000', name: 'Latina', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4091-terracina', code: '4091', name: 'Terracina', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '4100-lecce', code: '4100', name: 'Lecce', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4101-casarano', code: '4101', name: 'Casarano', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4190-nardo', code: '4190', name: 'Nardò', medicalChecks: true, artisansTraders: true, otherContributions: false },
  { id: '4200-livorno', code: '4200', name: 'Livorno', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4201-piombino', code: '4201', name: 'Piombino', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4300-lucca', code: '4300', name: 'Lucca', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4400-macerata', code: '4400', name: 'Macerata', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4500-mantova', code: '4500', name: 'Mantova', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4600-massa-carrara', code: '4600', name: 'Massa Carrara', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4700-matera', code: '4700', name: 'Matera', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4800-messina', code: '4800', name: 'Messina', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4891-santa-teresa-di-riva', code: '4891', name: 'Santa Teresa di Riva', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '4892-barcellona-pozzo-di-gotto', code: '4892', name: 'Barcellona Pozzo di Gotto', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '4894-milazzo', code: '4894', name: 'Milazzo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4900-milano', code: '4900', name: 'Milano', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4901-monza', code: '4901', name: 'Monza', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4902-milano-nord', code: '4902', name: 'Milano Nord', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4903-milano-missori', code: '4903', name: 'Milano Missori', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4904-milano-fiori', code: '4904', name: 'Milano Fiori', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4905-milano-corvetto', code: '4905', name: 'Milano Corvetto', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4908-milano-legnano', code: '4908', name: 'Milano Legnano', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4909-milano-seregno-c-o', code: '4909', name: 'Milano Seregno (C.O.)', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4927-lodi', code: '4927', name: 'Lodi', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4955-sesto-san-giovanni', code: '4955', name: 'Sesto San Giovanni', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '4979-vimercate', code: '4979', name: 'Vimercate', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '4991-melegnano', code: '4991', name: 'Melegnano', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '4995-desio-c-o', code: '4995', name: 'Desio (C.O.)', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5000-modena', code: '5000', name: 'Modena', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5094-sassuolo', code: '5094', name: 'Sassuolo', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '5100-napoli', code: '5100', name: 'Napoli', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5101-castellammare-di-stabia', code: '5101', name: 'Castellammare di Stabia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5102-nola', code: '5102', name: 'Nola', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5103-napoli-arzano', code: '5103', name: 'Napoli Arzano', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5104-napoli-soccavo', code: '5104', name: 'Napoli Soccavo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5105-napoli-vomero', code: '5105', name: 'Napoli Vomero', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5106-pozzuoli', code: '5106', name: 'Pozzuoli', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5199-giugliano', code: '5199', name: 'Giugliano', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '5200-novara', code: '5200', name: 'Novara', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5290-v-c-o-verbano-cusio-ossola', code: '5290', name: 'V.C.O. - Verbano Cusio Ossola', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5300-nuoro', code: '5300', name: 'Nuoro', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5400-padova', code: '5400', name: 'Padova', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5490-cittadella', code: '5490', name: 'Cittadella', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '5500-palermo', code: '5500', name: 'Palermo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5502-palermo-sud-ovest', code: '5502', name: 'Palermo Sud Ovest', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5503-carini', code: '5503', name: 'Carini', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5593-bagheria', code: '5593', name: 'Bagheria', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5600-parma', code: '5600', name: 'Parma', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5700-pavia', code: '5700', name: 'Pavia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5791-vigevano', code: '5791', name: 'Vigevano', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '5800-perugia', code: '5800', name: 'Perugia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5801-citta-di-castello', code: '5801', name: 'Citta\' di Castello', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5890-foligno', code: '5890', name: 'Foligno', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '5900-pesaro', code: '5900', name: 'Pesaro', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '5992-fano', code: '5992', name: 'Fano', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '6000-pescara', code: '6000', name: 'Pescara', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '6100-piacenza', code: '6100', name: 'Piacenza', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '6200-pisa', code: '6200', name: 'Pisa', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '6300-pistoia', code: '6300', name: 'Pistoia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '6400-potenza', code: '6400', name: 'Potenza', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '6490-melfi', code: '6490', name: 'Melfi', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '6500-ragusa', code: '6500', name: 'Ragusa', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '6590-modica', code: '6590', name: 'Modica', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '6600-ravenna', code: '6600', name: 'Ravenna', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '6691-lugo', code: '6691', name: 'Lugo', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '6700-reggio-calabria', code: '6700', name: 'Reggio Calabria', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '6790-palmi', code: '6790', name: 'Palmi', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '6791-locri', code: '6791', name: 'Locri', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '6800-reggio-emilia', code: '6800', name: 'Reggio Emilia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '6891-guastalla', code: '6891', name: 'Guastalla', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '6900-rieti', code: '6900', name: 'Rieti', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7000-roma', code: '7000', name: 'Roma', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7001-roma-eur', code: '7001', name: 'Roma Eur', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7002-roma-monteverde', code: '7002', name: 'Roma Monteverde', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7003-roma-ostia-lido', code: '7003', name: 'Roma Ostia Lido', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7004-roma-montesacro', code: '7004', name: 'Roma Montesacro', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7005-roma-centro', code: '7005', name: 'Roma Centro', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7006-civitavecchia', code: '7006', name: 'Civitavecchia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7009-roma-casilino-prenestino', code: '7009', name: 'Roma Casilino Prenestino', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7010-roma-tuscolano', code: '7010', name: 'Roma Tuscolano', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7012-roma-aurelio', code: '7012', name: 'Roma Aurelio', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7013-roma-tiburtino', code: '7013', name: 'Roma Tiburtino', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7014-roma-flaminio', code: '7014', name: 'Roma Flaminio', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7015-pomezia', code: '7015', name: 'Pomezia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7074-grottaferrata', code: '7074', name: 'Grottaferrata', medicalChecks: true, artisansTraders: true, otherContributions: false },
  { id: '7091-tivoli', code: '7091', name: 'Tivoli', medicalChecks: true, artisansTraders: true, otherContributions: false },
  { id: '7092-velletri', code: '7092', name: 'Velletri', medicalChecks: true, artisansTraders: true, otherContributions: false },
  { id: '7094-monterotondo', code: '7094', name: 'Monterotondo', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '7095-anzio', code: '7095', name: 'Anzio', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '7096-palestrina', code: '7096', name: 'Palestrina', medicalChecks: true, artisansTraders: true, otherContributions: false },
  { id: '7099-guidonia', code: '7099', name: 'Guidonia', medicalChecks: true, artisansTraders: true, otherContributions: false },
  { id: '7100-rovigo', code: '7100', name: 'Rovigo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7200-salerno', code: '7200', name: 'Salerno', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7201-nocera-inferiore', code: '7201', name: 'Nocera Inferiore', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7202-battipaglia', code: '7202', name: 'Battipaglia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7300-sassari', code: '7300', name: 'Sassari', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7390-olbia', code: '7390', name: 'Olbia', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '7400-savona', code: '7400', name: 'Savona', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7500-siena', code: '7500', name: 'Siena', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7600-siracusa', code: '7600', name: 'Siracusa', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7601-noto', code: '7601', name: 'Noto', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7700-sondrio', code: '7700', name: 'Sondrio', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7800-taranto', code: '7800', name: 'Taranto', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '7890-manduria', code: '7890', name: 'Manduria', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '7900-teramo', code: '7900', name: 'Teramo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8000-terni', code: '8000', name: 'Terni', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8100-torino', code: '8100', name: 'Torino', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8101-moncalieri', code: '8101', name: 'Moncalieri', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8102-ivrea', code: '8102', name: 'Ivrea', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8103-torino-nord', code: '8103', name: 'Torino Nord', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8103-torino-sud', code: '8103', name: 'Torino Sud', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8105-pinerolo', code: '8105', name: 'Pinerolo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8106-collegno', code: '8106', name: 'Collegno', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8110-torino-lingotto', code: '8110', name: 'Torino Lingotto', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8191-orbassano', code: '8191', name: 'Orbassano', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '8192-chieri', code: '8192', name: 'Chieri', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '8193-chivasso', code: '8193', name: 'Chivasso', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '8200-trapani', code: '8200', name: 'Trapani', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8290-marsala', code: '8290', name: 'Marsala', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8300-trento', code: '8300', name: 'Trento', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8400-treviso', code: '8400', name: 'Treviso', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8490-conegliano-c-o', code: '8490', name: 'Conegliano C.O.', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8500-trieste', code: '8500', name: 'Trieste', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8600-udine', code: '8600', name: 'Udine', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8691-cervignano-del-friuli', code: '8691', name: 'Cervignano del Friuli', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '8700-varese', code: '8700', name: 'Varese', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8790-busto-arsizio-c-o', code: '8790', name: 'Busto Arsizio C.O.', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8800-venezia', code: '8800', name: 'Venezia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8801-san-dona-di-piave', code: '8801', name: 'San Dona\' di Piave', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8891-chioggia', code: '8891', name: 'Chioggia', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '8900-vercelli', code: '8900', name: 'Vercelli', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '8901-biella', code: '8901', name: 'Biella', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '9000-verona', code: '9000', name: 'Verona', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '9090-legnago', code: '9090', name: 'Legnago', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { id: '9100-vicenza', code: '9100', name: 'Vicenza', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '9200-viterbo', code: '9200', name: 'Viterbo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '9300-pordenone', code: '9300', name: 'Pordenone', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { id: '9400-isernia', code: '9400', name: 'Isernia', medicalChecks: true, artisansTraders: true, otherContributions: true },
];

export function findInpsOfficeById(id: string): InpsOffice | undefined {
  return INPS_OFFICES.find((o) => o.id === id);
}

export function findInpsOffice(code: string): InpsOffice | undefined {
  return INPS_OFFICES.find((o) => o.code === code.padStart(4, '0'));
}

/** All rows for a code (the official table can list the same code more than once). */
export function findInpsOffices(code: string): InpsOffice[] {
  return INPS_OFFICES.filter((o) => o.code === code.padStart(4, '0'));
}

/** True when the code exists and accepts "other contributions" (Gestione Separata). */
export function isValidInpsOfficeForGestioneSeparata(code: string): boolean {
  return findInpsOffice(code)?.otherContributions === true;
}

/** True when the id exists and the office accepts "other contributions" (Gestione Separata). */
export function isValidInpsOfficeIdForGestioneSeparata(id: string): boolean {
  return findInpsOfficeById(id)?.otherContributions === true;
}
