/**
 * Social security entities paid in the F24 section "Altri enti previdenziali e assicurativi" (second box): professional
 * funds with an F24 entity code in the AdE table "Codici altri Enti Previdenziali ed Assicurativi" (28/04/2026,
 * `ade-codici-altri-enti-2026-04-28`), with the reasons ("causali contributo") of each entity's AdE table and resolutions.
 * The resolutions fill the box the same way: the reasons go "nel campo “causale contributo”, esclusivamente in
 * corrispondenza delle somme indicate nella colonna “importi a debito versati”", with no "codice sede" and no "codice
 * posizione", except where an entity says otherwise (CNPADC). The amounts and dates are not in these sources: each
 * fund sets them in its own rules.
 */

/** How the "periodo di riferimento" is written. */
export type OtherEntityPeriod =
  /** "da mm/aaaa" and "a mm/aaaa", start not after the end. */
  | 'MONTH_YEAR'
  /** Only the year, in the "da" field ("Formato AAAA"); the end is zero (ENPAP). */
  | 'YEAR';

/**
 * Whether a paid reason is deducted from the flat-rate income (LM35, "contributi previdenziali [...] versati [...] in
 * ottemperanza a disposizioni di legge"): YES for the personal contribution ("soggettivo"); NO for the contribution
 * charged on invoices ("integrativo": "e' indeducibile dal reddito dei contribuenti", AdE Ris. 69/E/2006); MIXED when one
 * reason pays both; UNKNOWN when no source was checked (maternity, redemption, sanctions, interest...). Only YES is
 * counted automatically; the taxpayer enters the rest by hand.
 */
export type ContributionDeduction = 'YES' | 'NO' | 'MIXED' | 'UNKNOWN';

export interface OtherEntityReason {
  /** Causale, e.g. "E100". */
  code: string;
  /** Description as in the AdE table or resolution. */
  description: string;
  deduction: ContributionDeduction;
}

export interface OtherEntity {
  /** Codice ente, e.g. "0013". */
  code: string;
  /** Short name, e.g. "Cassa Forense". */
  name: string;
  /** TipoCassa of the same fund in FatturaPA (TC01...), to propose the entity from the profile. */
  fundType?: string;
  period: OtherEntityPeriod;
  /** Rule for the "periodo di riferimento", in plain Italian, as the source says (e.g. competence or payment month). */
  periodRule: string;
  /** "codice posizione": NONE (left empty) or REQUIRED (e.g. CNPADC, a code generated by the fund for each payment). */
  positionCode: 'NONE' | 'REQUIRED';
  reasons: OtherEntityReason[];
  /** Registry ids (docs/fonti/registro.json) of the AdE table and resolutions used. */
  sourceIds: string[];
}

export const OTHER_ENTITIES: OtherEntity[] = [
  {
    code: '0006',
    name: 'ENPACL',
    fundType: 'TC08',
    period: 'MONTH_YEAR',
    periodRule: 'Mese e anno di inizio e di fine del periodo di competenza del contributo ("il periodo di competenza del contributo da versare, nel formato MM/AAAA").',
    positionCode: 'NONE',
    reasons: [
      { code: 'E050', description: 'Contribuzione soggettiva - pari al 12% del reddito professionale', deduction: 'YES' },
      { code: 'E051', description: "Contribuzione integrativa - pari al 4% del volume d'affari IVA", deduction: 'NO' },
      { code: 'E052', description: 'Contribuzione facoltativa aggiuntiva pari a 500 euro o multipli', deduction: 'UNKNOWN' },
      { code: 'E053', description: 'Contribuzione in acconto - contribuzione soggettiva e integrativa', deduction: 'MIXED' },
      { code: 'E054', description: 'Contribuzione per maternità - per oneri della relativa indennità', deduction: 'UNKNOWN' },
      { code: 'E055', description: 'Rateazione - morosità contributiva', deduction: 'UNKNOWN' },
      { code: 'E056', description: 'Ravvedimento - morosità contributiva', deduction: 'UNKNOWN' },
      { code: 'E057', description: 'Contribuzione volontaria ai fini della pensione di vecchiaia', deduction: 'UNKNOWN' },
      { code: 'E058', description: 'Sanzioni fisse o percentuali', deduction: 'UNKNOWN' },
      { code: 'E059', description: 'Ricongiunzione - onere a carico del richiedente', deduction: 'UNKNOWN' },
      { code: 'E060', description: 'Riscatto militare - onere a carico del richiedente', deduction: 'UNKNOWN' },
      { code: 'E061', description: 'Riscatto laurea - onere a carico del richiedente', deduction: 'UNKNOWN' },
      { code: 'E062', description: 'Riscatto praticantato - onere a carico del richiedente', deduction: 'UNKNOWN' },
      { code: 'E063', description: 'Riscatto quote ridotte - onere a carico del richiedente', deduction: 'UNKNOWN' },
      { code: 'E064', description: 'Altro - causale generica', deduction: 'UNKNOWN' },
    ],
    sourceIds: ['ade-causali-enpacl-2014-05-30', 'ade-ris-55e-2014'],
  },
  {
    code: '0007',
    name: 'ENPAP',
    fundType: 'TC21',
    period: 'YEAR',
    periodRule: 'Solo l\'anno, senza mese ("Formato AAAA"), con la fine valorizzata a zero: l\'anno di competenza del contributo; per ERC2 l\'anno in cui viene effettuato il versamento.',
    positionCode: 'NONE',
    reasons: [
      { code: 'ECTR', description: 'Contributi (Acconto/Saldo)', deduction: 'UNKNOWN' },
      { code: 'ERPS', description: 'Riscatto periodi di studio', deduction: 'UNKNOWN' },
      { code: 'EAPR', description: "Riscatto anni di esercizio professionale precedenti la fondazione dell'Ente", deduction: 'UNKNOWN' },
      { code: 'ESNZ', description: 'Sanzioni', deduction: 'UNKNOWN' },
      { code: 'EINT', description: 'Interessi', deduction: 'UNKNOWN' },
      { code: 'ERC2', description: 'Regolarizzazione contributiva', deduction: 'UNKNOWN' },
    ],
    sourceIds: ['ade-causali-enpap-2022-01-21', 'ade-ris-60e-2015', 'ade-ris-4e-2022'],
  },
  {
    code: '0008',
    name: 'EPAP',
    fundType: 'TC18',
    period: 'MONTH_YEAR',
    periodRule: 'Mese e anno del versamento ("il mese e l\'anno del versamento, nel formato MM/AAAA").',
    positionCode: 'NONE',
    reasons: [{ code: 'E065', description: 'Contribuzione previdenziale obbligatoria', deduction: 'UNKNOWN' }],
    sourceIds: ['ade-causali-epap-2015-02-13', 'ade-ris-14e-2015'],
  },
  {
    code: '0009',
    name: 'EPPI',
    fundType: 'TC17',
    period: 'MONTH_YEAR',
    periodRule: 'Mese e anno in cui si paga ("il mese e l\'anno nel quale si effettua il versamento, nel formato MM/AAAA").',
    positionCode: 'NONE',
    // E066, E067 and E071 were suppressed by Ris. 52/E/2018; E068, suppressed by the same resolution, was reactivated by Ris. 53/E/2023.
    reasons: [
      { code: 'E068', description: 'Saldo contributivo - art. 8, c. 1, del Regolamento di previdenza', deduction: 'UNKNOWN' },
      { code: 'E069', description: "Capitale e/o spese legali - art. 8, c. 4 e 6, Regolamento per l'attuazione delle attività di previdenza", deduction: 'UNKNOWN' },
      { code: 'E070', description: "Interessi di mora e sanzioni e/o spese legali - art. 8, c. 5 e 6, Regolamento per l'attuazione delle attività di previdenza", deduction: 'UNKNOWN' },
      { code: 'E072', description: 'Spese legali a seguito di procedimento giudiziario', deduction: 'UNKNOWN' },
      { code: 'E073', description: 'Recupero oneri pensionistici', deduction: 'UNKNOWN' },
    ],
    sourceIds: ['ade-causali-eppi-2024-06-26', 'ade-ris-19e-2015', 'ade-ris-52e-2018', 'ade-ris-53e-2023', 'ade-ris-32e-2024'],
  },
  {
    code: '0010',
    name: 'CNPR',
    fundType: 'TC06',
    period: 'MONTH_YEAR',
    periodRule: 'Mese e anno di inizio e di fine del periodo di competenza del contributo ("il periodo di competenza del contributo da versare, nel formato MM/AAAA").',
    positionCode: 'NONE',
    reasons: [
      { code: 'E075', description: 'Contributi anno corrente', deduction: 'UNKNOWN' },
      { code: 'E076', description: 'Contributi anni precedenti', deduction: 'UNKNOWN' },
      { code: 'E077', description: 'Sanzioni, interessi e spese legali anno corrente', deduction: 'UNKNOWN' },
      { code: 'E078', description: 'Sanzioni, interessi e spese legali anni precedenti', deduction: 'UNKNOWN' },
      { code: 'E079', description: 'Contributi da ricongiunzione', deduction: 'UNKNOWN' },
      { code: 'E080', description: 'Contributi da riscatto', deduction: 'UNKNOWN' },
      { code: 'E081', description: 'Contributi volontari', deduction: 'UNKNOWN' },
      { code: 'E082', description: 'Rateazione', deduction: 'UNKNOWN' },
    ],
    sourceIds: ['ade-causali-cnpr-2016-12-06', 'ade-ris-111e-2016'],
  },
  {
    code: '0011',
    name: 'Inarcassa',
    fundType: 'TC04',
    period: 'MONTH_YEAR',
    periodRule: 'Mese e anno di competenza del contributo ("il mese e l\'anno di competenza del contributo da versare, nel formato MM/AAAA").',
    positionCode: 'NONE',
    reasons: [
      { code: 'E085', description: 'Contribuzione soggettiva minima', deduction: 'YES' },
      { code: 'E086', description: 'Contribuzione soggettiva conguaglio', deduction: 'YES' },
      { code: 'E087', description: 'Contribuzione integrativa minima', deduction: 'NO' },
      { code: 'E088', description: 'Contribuzione integrativa conguaglio', deduction: 'NO' },
      { code: 'E089', description: 'Contribuzione per maternità/paternità', deduction: 'UNKNOWN' },
      { code: 'E090', description: 'Contribuzione società di ingegneria', deduction: 'UNKNOWN' },
      // The AdE table writes "NARCASSA"; the description follows Ris. 66/E/2023.
      { code: 'E111', description: 'Contributi e interessi da riscatto deroga soggettivo', deduction: 'UNKNOWN' },
      { code: 'E112', description: 'Contributi e interessi da ricongiunzione', deduction: 'UNKNOWN' },
      { code: 'E113', description: 'Contributi e interessi da riscatto', deduction: 'UNKNOWN' },
      { code: 'E114', description: 'Contributo soggettivo facoltativo', deduction: 'UNKNOWN' },
      { code: 'E115', description: 'Integrazione contribuzione ridotta giovani soggettiva e integrativa', deduction: 'MIXED' },
      { code: 'E116', description: 'Contributo soggettivo anni precedenti', deduction: 'UNKNOWN' },
      { code: 'E117', description: 'Contributo integrativo anni precedenti', deduction: 'NO' },
      { code: 'E118', description: 'Sanzioni e interessi soggettivo', deduction: 'UNKNOWN' },
      { code: 'E119', description: 'Sanzioni e interessi integrativo', deduction: 'UNKNOWN' },
      { code: 'E120', description: 'Interessi maternità / paternità', deduction: 'UNKNOWN' },
      { code: 'E121', description: 'Oneri di recupero', deduction: 'UNKNOWN' },
    ],
    sourceIds: ['ade-causali-inarcassa-2023-12-05', 'ade-ris-22e-2020', 'ade-ris-66e-2023'],
  },
  {
    code: '0012',
    name: 'ENPAB',
    fundType: 'TC19',
    period: 'MONTH_YEAR',
    periodRule: 'Mese e anno di competenza del contributo ("il mese e l\'anno di competenza del contributo da versare, nel formato MM/AAAA").',
    positionCode: 'NONE',
    reasons: [
      { code: 'E095', description: 'Contributi correnti', deduction: 'UNKNOWN' },
      { code: 'E096', description: 'Contributi pregressi', deduction: 'UNKNOWN' },
      { code: 'E097', description: 'Rateazioni contributive', deduction: 'UNKNOWN' },
      { code: 'E098', description: 'Riscatti', deduction: 'UNKNOWN' },
      { code: 'E099', description: 'Contributi volontari', deduction: 'UNKNOWN' },
    ],
    sourceIds: ['ade-causali-enpab-2020-07-30', 'ade-ris-45e-2020'],
  },
  {
    code: '0013',
    name: 'Cassa Forense',
    fundType: 'TC01',
    period: 'MONTH_YEAR',
    periodRule: 'Mese e anno di competenza del contributo ("il mese e l\'anno di competenza del contributo da versare, nel formato MM/AAAA").',
    positionCode: 'NONE',
    reasons: [
      { code: 'E100', description: 'Contributo soggettivo minimo', deduction: 'YES' },
      { code: 'E101', description: 'Contributo di maternità', deduction: 'UNKNOWN' },
      { code: 'E102', description: 'Contributo soggettivo autoliquidazione (Mod. 5)', deduction: 'YES' },
      { code: 'E103', description: 'Contributo integrativo autoliquidazione (Mod. 5)', deduction: 'NO' },
      { code: 'E104', description: 'Riscatto art. 37 Reg. Unico Prev. Forense', deduction: 'UNKNOWN' },
      { code: 'E105', description: 'Integrazione contr. minimo soggettivo (12 mesi)', deduction: 'YES' },
      { code: 'E106', description: 'Interessi integrazione contr. minimo soggettivo', deduction: 'UNKNOWN' },
      // The AdE table says "contributo minimo garantito"; the description follows Ris. 24/E/2023.
      { code: 'E107', description: 'Contributo minimo integrativo', deduction: 'NO' },
    ],
    sourceIds: ['ade-causali-cassa-forense-2023-06-05', 'ade-ris-1e-2021', 'ade-ris-34e-2021', 'ade-ris-56e-2021', 'ade-ris-24e-2023'],
  },
  {
    code: '0015',
    name: 'CNPADC',
    fundType: 'TC02',
    period: 'MONTH_YEAR',
    periodRule: 'Da gennaio a dicembre dell\'anno del versamento ("da mm/aaaa" il mese di gennaio (01) e "a mm/aaaa" il mese di dicembre (12) dell\'anno del versamento).',
    positionCode: 'REQUIRED',
    reasons: [{ code: 'E150', description: 'Adempimenti CNPADC', deduction: 'UNKNOWN' }],
    sourceIds: ['ade-causali-cnpadc', 'ade-ris-13e-2026'],
  },
];

export function findOtherEntity(code: string): OtherEntity | undefined {
  return OTHER_ENTITIES.find((e) => e.code === code);
}
